version: 0.1

phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - jekyll build
  post_build:
    commands:
      - aws s3 sync _site s3://pinkimpact-static-dev --delete
artifacts:
  files:
    - check/index.html
